# Makefile for PTrack pass

# Path to top level of LLVM hierarchy
# WARNING: This must the the source AND the build directory!
LEVEL = ../../..

# Name of the library to build
LIBRARYNAME = LLVMPTrack

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
LOADABLE_MODULE = 1

# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
